### PR TITLE
add custom BoxShadow instead of just color

### PR DESCRIPTION
**Pull request by quetool**
Just a little change to add custom BoxShadow

### CODE REVIEW

**Comment by AndreHaueisen** [comment]
Hi @quetool 
You make a valid point. I think we can remove the `shadowColor` property for the sake of simplicity and leave only `boxShadow`.

If you can update it will be great, if not I can do it in a few weeks.
This should be included in the next release together with some IOS bug fixes.

Thanks for the feedback and help.
Cheers.

**Comment by quetool** [comment]
Hi @AndreHaueisen, thanks for your reply. Sure, I'll do in a moment! Thanks!

**Comment by quetool** [comment]
Did it! Thanks for your repo, it is just great!

**Comment by facundomedica** [comment]
@AndreHaueisen this looks good to me too, could you please merge it? Thanks!

**Comment by AndreHaueisen** [comment]
Sorry about the delay. Have a lot going on these days.
Thanks for the help guys.

**Comment by quetool** [comment]
@AndreHaueisen thanks!

**Pull request merged**
