### PR TITLE
Fix issue #110

### PR DESCRIPTION
**Pull request by valterh4ck3r**
Fix override install method issue : https://github.com/AndreHaueisen/flushbar/issues/110

### CODE REVIEW

**Comment by maxgmer** [comment]
pls merge it, need so badly xD

**Comment by fauzipadlaw** [comment]
pls merge it, need so badly xD

**Comment by alalawy** [comment]
please merge it

**Comment by Frozmen** [comment]
@AndreHaueisen ping :)

**Comment by ebastuart** [comment]
waiting for merge :)

**Comment by judeosbert** [comment]
Please merge this ASAP. I cant build my desktop app 😢 .

**Comment by valterh4ck3r** [comment]
Use my fork if you need.

https://github.com/valterh4ck3r/flushbar

**Comment by ebastuart** [comment]
For everybody who doesn't know how to import the package:


```
flushbar:

    git:

      url: https://github.com/valterh4ck3r/flushbar.git
```

**Comment by jagmit** [comment]
@AndreHaueisen shouldn't these changes get a new minor version and pub.dev release?

**Comment by fauzipadlaw** [comment]
@j5ingh that will be causing error on flutter stable/beta, since this issue appears on flutter channel master, i guess

can use master version of this package if you are on flutter channel master

**Comment by jagmit** [comment]
@fauzipadlaw  Oh sure, you are right

**Comment by rayliverified** [comment]
Please consider releasing this fix in a minor version prerelease.
For example, `1.10.0-dev.1`

https://dart.dev/tools/pub/publishing

It would be really helpful for us using the package in our projects, thanks!

**Comment by draganjovanovic1** [comment]
Any news on the new package release? Thanks.

**Comment by amirbennasr-smic** [comment]
i'm still waiting for this to be fixed ,please merge 👍

**Comment by djpnewton** [comment]
import package like so to use this fix:
```
flushbar:
   git:
     url: https://github.com/AndreHaueisen/flushbar.git
     ref: 13c55a8
```

**Comment by NicolasLehoux** [comment]
Tks this fix worked for me. I wish for a release soon

**Comment by DaraGboyega** [comment]
Please merge as soon as you can fam

**Comment by sarinupreti** [comment]
yes please merge ASAP

**Comment by kbokarius** [comment]
I'm still getting the error even after adding this to my pubspec.yaml:

```
flushbar:
    git:
      url: https://github.com/valterh4ck3r/flushbar.git
```

**Comment by jagmit** [comment]
> I'm still getting the error even after adding this to my pubspec.yaml:
> 
> ```
> flushbar:
>     git:
>       url: https://github.com/valterh4ck3r/flushbar.git
> ```
@kbokarius 
Maybe try ```flutter clean```' and rerun `flutter pub get`

**Comment by barahijawi** [comment]
just edit the code in flushbar_route.dart you can find it under External Libraries/Dart Packages/flusher-1.10.0/
line 316 to 328 replace with this code

  ```
@override
  void install(OverlayEntry) {
    assert(!_transitionCompleter.isCompleted,
        'Cannot install a $runtimeType after disposing it.');
    _controller = createAnimationController();
    assert(_controller != null,
        '$runtimeType.createAnimationController() returned null.');
    _filterBlurAnimation = createBlurFilterAnimation();
    _filterColorAnimation = createColorFilterAnimation();
    _animation = createAnimation();
    assert(_animation != null, '$runtimeType.createAnimation() returned null.');
    super.install(OverlayEntry);
  }
```

use this code to show flushbar (example) , always don't forget ..show();
```
 Flushbar(
        title: "Hey Ninja",
        message:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        flushbarPosition: FlushbarPosition.TOP,
        flushbarStyle: FlushbarStyle.FLOATING,
        reverseAnimationCurve: Curves.decelerate,
        forwardAnimationCurve: Curves.elasticOut,
        backgroundColor: Colors.red,
        boxShadows: [
          BoxShadow(
              color: Colors.blue[800],
              offset: Offset(0.0, 2.0),
              blurRadius: 3.0)
        ],
        backgroundGradient:
            LinearGradient(colors: [Colors.blueGrey, Colors.black]),
        isDismissible: false,
        duration: Duration(seconds: 4),
        icon: Icon(
          Icons.check,
          color: Colors.greenAccent,
        ),
        mainButton: FlatButton(
          onPressed: () {},
          child: Text(
            "CLAP",
            style: TextStyle(color: Colors.amber),
          ),
        ),
        showProgressIndicator: true,
        progressIndicatorBackgroundColor: Colors.blueGrey,
        titleText: Text(
          "Hello Hero",
          style: TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 20.0,
              color: Colors.yellow[600],
              fontFamily: "ShadowsIntoLightTwo"),
        ),
        messageText: Text(
          "You killed that giant monster in the city. Congratulations!",
          style: TextStyle(
              fontSize: 18.0,
              color: Colors.green,
              fontFamily: "ShadowsIntoLightTwo"),
        ),
      )..show(context); 
```

Good Luck.

**Pull request merged**
