### PR TITLE
Add ability to dismiss when clicking/tapping overlay #71

### PR DESCRIPTION
**Pull request by mcoolidge**

### CODE REVIEW

**Comment by AndreHaueisen** [comment]
Hi @mcoolidge 
Thanks for your help!
I took a look at your code and something came to mind. Do you think we could embed the dismissible overlay functionality inside the already existing `isDismissible`?
Just trying to avoid the creation of another variable.
Would that generate any downsides for you?

**Comment by mcoolidge** [comment]
Sure! That implies this will be the default behavior if they are dismissible. I didn't want to assume, so I added the extra variable for flexibility, but that works for me.

**Comment by mcoolidge** [comment]
Changes were committed. Let me know if that's the route we want to take, or if another variable would be preferable for extra flexibility.

FYI: I added an example app to the project for testing, but it's not in the commit. Let me know if that's something you would be interested in adding to the project.

**Comment by AndreHaueisen** [comment]
Thanks @mcoolidge 
I tested the code. Flushbar needs to animate back on dismissal. I will make some changes over here and push an update today

**Pull request closed without merging**
